<?php
use App\Entity\Product;
use PHPUnit\Framework\TestCase;
use App\Models\Http;

class ProductTest extends \App\Tests\DbTestCase {
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function getDataSet()
    {
        return new \PHPUnit\DbUnit\DataSet\YamlDataSet(dirname(__FILE__)."/../dataset/product.yml");
    }


    public function test_db_connect(){
        //单元测试 独立的方法块。

        // $_COOKIE -->$_session_id---> $_SESSION // 模拟cookie

        islogin(); // session 里面 $session['_id']  $_session_id;

        $this->assertEquals(2,$this->getConnection()->getRowCount('product'));
    }

    public function test_create_table(){
        $this->markTestIncomplete(          '此测试目前尚未实现。'        );
    }
}
