<?php
use App\Entity\Product;
use PHPUnit\Framework\TestCase;
use App\Models\Http;

class ProductTest extends \App\Tests\DbTestCase {
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function getDataSet()
    {
        return new \PHPUnit\DbUnit\DataSet\YamlDataSet(dirname(__FILE__)."/../dataset/product.yml");
    }

    public function test_db_connect(){
        $db = app('db');
        $product = new Product();
        $product->setName('hello');

        $entityManager = $db->manager;
        $id = $entityManager->find(Product::class,2);
        $this->assertEquals(2,$this->getConnection()->getRowCount());
    }

    public function test_create_table(){
        $this->markTestIncomplete(          '此测试目前尚未实现。'        );
    }
}
